#! /usr/bin/env bash

_check_server() {

    #checks if the server is running
    if [[ "$(pg_ctl status)" == "pg_ctl: no server running" ]]; then
        echo &&
            rich --print "[bold][red]==>[/red] Postgres server is not running, starting the server..." &&
            pg_ctl start -D /usr/local/var/postgres >/dev/null 2>&1
    else
        echo &&
            rich --print "[bold][cyan]==>[/cyan] Postgres server is already running."
    fi

}

_create_table() {

    # define parameters
    local table_name="$1"
    local db_name="$2"

    echo &&
        rich --print "[bold][cyan]==>[/cyan] Creating table [blue]${table_name}[/cyan] in [blue]${db_name}[/blue] database..." &&
        psql -d "$db_name" -c "
            DROP TABLE IF EXISTS ${table_name};

            CREATE TABLE IF NOT EXISTS ${table_name} (
                numero_stazione SMALLINT PRIMARY KEY,
                nome_stazione TEXT,
                longitudine FLOAT,
                latitudine FLOAT,
                cluster SMALLINT,
                lon_cluster FLOAT,
                lat_cluster FLOAT,
                cluster_id_nil SMALLINT,
                cluster_nil TEXT
            );" &&
        echo

}

_import_data_into_postgres() {

    # define parameters
    local csv="$1"
    local table_name="$2"
    local db_name="$3"

    # store the columns of the csv as an array
    local cols
    cols="$(head -1 "$csv")"

    # copy the csv into the postgresql TABLE_NAME into the database DB_NAME
    echo &&
        rich --print "[bold][cyan]==>[/cyan] Importing data from [cyan]${csv}[/cyan] into [blue]${table_name}[/blue] table in [blue]${db_name}[/blue] database..." &&
        psql -d "$db_name" -c "
            SET datestyle TO iso, dmy;
            COPY ${table_name} (${cols}) FROM '${csv}' WITH DELIMITER ',' CSV HEADER;" &&
        rm "$csv" &&
        echo
}

# +------+
# | prep |
# +------+

command -v rich || {
    echo "Install rich first, e.g. \`pipx install rich\`"
    exit 1
}

# +------------------+
# | global variables |
# +------------------+

_INPUT_FILE="${1:-"$HOME/tesi/data/milan/bikemi-selected_stalls-clusters.csv"}"

_TABLE_NAME="${2:-"bikemi_stalls_clusters"}"
_SCHEMA="${3:-"bikemi_rentals"}"
_DB_NAME="${4:-"bikemi"}"

_TABLE="${_SCHEMA}.${_TABLE_NAME}"

# +------+
# | body |
# +------+

_check_server

_create_table "$_TABLE" "$_DB_NAME" && _import_data_into_postgres "$_INPUT_FILE" "$_TABLE" "$_DB_NAME"
