#! /usr/bin/env bash

# +------------------+
# | DEFINE FUNCTIONS |
# +------------------+

_get_bikemi_stalls_data() {

    local url="$1"
    local filename="$2"

    curl "$url" -o "$filename"
}

_process_stalls_data() {

    local target_file="$1"
    local destination_file="$2"
    local new_header="numero_stazione,nome,municipio,anno,geometry"

    xsv select 3,4,11,12,15 --delimiter ";" "$target_file" |
        sed "1s/.*/$new_header/" >"$destination_file" &&
        rm "$target_file"
}

_start_server() {

    local server="${1:-"/usr/local/var/postgres"}"

    #checks if the server is running
    if [[ "$(pg_ctl status)" == "pg_ctl: no server running" ]]; then
        echo &&
            rich --print "[bold][red]==>[/red] Postgres server is not running, starting the server..." &&
            pg_ctl start -D "$server" >/dev/null 2>&1
    else
        echo &&
            rich --print "[bold][cyan]==>[/cyan] Postgres server is already running."
    fi

}

_create_table() {

    # define parameters
    local table_name="$1"
    local db_name="$2"

    echo &&
        rich --print "[bold][blue]==>[/blue] Creating table [blue]${table_name}[/blue] in [blue]${db_name}[/blue] database..." &&
        psql -d "$db_name" -c "
            DROP TABLE IF EXISTS ${table_name};

            CREATE TABLE IF NOT EXISTS ${table_name} (
                numero_stazione SMALLINT PRIMARY KEY,
                nome_stazione TEXT,
                municipio SMALLINT,
                anno SMALLINT,
                geometry TEXT
            );" &&
        echo

}

_import_data_into_postgres() {

    # define parameters
    local csv="$1"
    local table_name="$2"
    local db_name="$3"

    # store the columns of the csv as an array
    local cols
    cols="$(head -1 "$csv")"

    # copy the csv into the postgresql TABLE_NAME into the database DB_NAME
    echo &&
        rich --print "[bold][cyan]==>[/cyan] Importing data from [cyan]${csv}[/cyan] into [blue]${table_name}[/blue] table in [blue]${db_name}[/blue] database..." &&
        psql -d "$db_name" -c "
            SET datestyle TO iso, dmy;
            COPY ${table_name} (${cols}) FROM '${csv}' WITH DELIMITER ',' CSV HEADER;" &&
        rm "$csv" &&
        echo

}

# +-------------+
# | GLOBAL VARS |
# +-------------+

command -v rich || {
    echo "Install rich first, e.g. \`pipx install rich\`"
    exit 1
}

_URL="https://dati.comune.milano.it/dataset/cc065002-cd21-4dcb-b84f-bba2fd9e0c86/resource/4c31029c-22c9-49f7-b145-91374feac41c/download/bikemi_stazioni.csv"

_TARGET_DIR="${1:-"$HOME/tesi/data/milan"}"
_FILE_NAME="${2:-"bikemi-stazioni.csv"}"
_PROCESSED_FILE="${_FILE_NAME/.csv/_processed.csv}"

_DB_NAME="bikemi"
_TABLE_NAME="bikemi_stalls"
_SERVER="/usr/local/var/postgres"

# +------+
# | BODY |
# +------+

pushd "$_TARGET_DIR" 1>/dev/null || exit

_get_bikemi_stalls_data "$_URL" "$_FILE_NAME"

_process_stalls_data "$_FILE_NAME" "$_PROCESSED_FILE"

_start_server "$_SERVER"

_create_table "$_TABLE_NAME" "$_DB_NAME"

_import_data_into_postgres "$_PROCESSED_FILE" "$_TABLE_NAME" "$_DB_NAME"

popd 1>/dev/null || exit
