#! /usr/bin/env bash

# _process_data () {
#     
#     local input_file="$1"
#     local output_file="$2"
# 
#     xsv select '!3' "$input_file" > "$output_file"
# }

_check_server () {

    #checks if the server is running
    if [[ "$(pg_ctl status)" == "pg_ctl: no server running" ]]; then
        echo -e "\n${BOLD}${RED}==> Postgres server is not running, starting the server...${RESET}"
        # starts the server, deletes output
        pg_ctl start -D /usr/local/var/postgres > /dev/null 2>&1
    else
        echo -e "\n${CYAN}${BOLD}==> Postgres server is already running.${RESET}"
    fi

}

_create_table () {

    # define parameters
    local table_name="$1"
    local db_name="$2"

    echo -e "\n${BOLD}${BLUE}=>${WHITE} Checking if table ${BLUE}${table_name}${WHITE} exists${RESET}"
    psql -d "$db_name" -c "
        DROP TABLE IF EXISTS ${table_name}; 
        
        CREATE TABLE IF NOT EXISTS ${table_name} (
            numero_stazione SMALLINT PRIMARY KEY,
            nome_stazione TEXT,
            longitudine FLOAT,
            latitudine FLOAT,
            cluster SMALLINT,
            lon_cluster FLOAT,
            lat_cluster FLOAT,
            cluster_id_nil SMALLINT,
            cluster_nil TEXT
        );" 
    echo ""

}

_import_data_into_postgres () {
    
    # define parameters
    local csv="$1"
    local table_name="$2"
    local db_name="$3"

    # store the columns of the csv as an array
    local cols
    cols="$( head -1 "$csv" )"
    
    # copy the csv into the postgresql TABLE_NAME into the database DB_NAME
    echo "${BOLD}${CYAN}==> ${WHITE}Copying ${CYAN}${csv} ${WHITE}to ${BLUE}${table_name} ${WHITE}in ${VIOLET}${db_name}${RESET}"
    psql -d "$db_name" -c "
        SET datestyle TO iso, dmy;
        COPY ${table_name}(${cols})
        FROM '${csv}'
        DELIMITER ','
        CSV HEADER;" \
        && rm "$csv"
}

# +------+
# | prep |
# +------+

# colored output
source formatting_colors

# +------------------+
# | global variables |
# +------------------+

_INPUT_FILE="${1:-"$HOME/tesi/data/milan/bikemi-selected_stalls-clusters.csv"}"

_TABLE_NAME="${2:-"bikemi_stalls_clusters"}"
_SCHEMA="${3:-"bikemi_rentals"}"
_DB_NAME="${4:-"bikemi"}"

_TABLE="${_SCHEMA}.${_TABLE_NAME}"

# +------+
# | body |
# +------+

_check_server

_create_table "$_TABLE" "$_DB_NAME" && _import_data_into_postgres "$_INPUT_FILE" "$_TABLE" "$_DB_NAME"
