#!/usr/bin/env bash

command -v rich || {
    echo "Install rich first, e.g. \`pipx install rich\`"
    exit 1
}

_BREW_CACHE="$HOME/.cache/brew/cache"

if [[ ! -d "$_BREW_CACHE" ]]; then
    mkdir -p "$_BREW_CACHE"
fi

rich --print "\n[bold]Exporting Homebrew formulae to [blue]$_BREW_CACHE..." && brew leaves -r >"${_BREW_CACHE}"/brew_formulae.txt

rich --print "\n[bold]Exporting Homebrew casks to [blue]$_BREW_CACHE..." && brew list --cask >"${_BREW_CACHE}"/brew_casks.txt
