#!/usr/bin/env bash

command -v rich 1>/dev/null || {
    echo "Install rich first, e.g. \`pipx install rich\`"
    exit 1
}

rich --print "[bold]Removing unused formulae..." && brew leaves -p | xargs -L 1 brew uninstall

rich --print "[bold]Removing lockfiles and outdated downloads..." && brew cleanup -s
