#!/usr/bin/env bash

source "$ZDOTDIR/colors.zsh"

_BREW_CACHE="$HOME/.cache/brew/cache"

if [[ ! -d "$_BREW_CACHE" ]]; then
    mkdir -p "$_BREW_CACHE"
fi

echo -e "\n${BOLD}Exporting Homebrew formulae to ${CYAN}${_BREW_CACHE}${RESET}${BOLD}...${RESET}"
brew list --formula > "${_BREW_CACHE}"/brew_formulae.txt

echo -e "\n${BOLD}Exporting Homebrew casks to ${CYAN}${_BREW_CACHE}${RESET}${BOLD}...${RESET}"
brew list --cask > "${_BREW_CACHE}"/brew_cask.txt
