#!/usr/bin/env bash

command -v rich 1>/dev/null || {
    echo "Install rich first, e.g. \`pipx install rich\`"
    exit 1
}

echo
rich --print --emoji ":beer: [bold]Initialising [blue]brew update[/blue]..." &&
    brew update &&
    rich --print "[bold]Homebrew has been updated."

echo
rich --print --emoji ":beer: [bold]Initialising [blue]brew upgrade[/blue]..." &&
    brew upgrade &&
    rich --print "[bold]Homebrew has been upgraded."

rich --print --emoji ":beers: [bold]Homebrew is up to date: cheers!"
