#! /usr/bin/env bash

# saves the packages of an environment to a specified directory and removes it. 

# this is necessary, otherwise won't find the command. see here:
# https://github.com/conda/conda/issues/7980#issuecomment-441358406
source "$CONDA_ROOT/etc/profile.d/conda.sh"

# source colors. this has to be done because subprocesses do not inherit environmental variables
source "$ZDOTDIR/colors.zsh"

# define your own backup directory - mine is at ~/.config/conda_envs_backups
CONDA_ENVS_BACKUP_DIR="${CONFIG}/conda_envs_backups"

# check if the directory where the package list exists, else make it
if [[ ! -d "$CONDA_ENVS_BACKUP_DIR" ]]; then
    echo -e "\nBackup directory created at "${CONDA_ENVS_BACKUP_DIR}"."
    mkdir ${CONDA_ENVS_BACKUP_DIR} 
else
    echo -e "\nBackup directory already exists at "${CONDA_ENVS_BACKUP_DIR}"."
fi

# $@ indicates every argument of the script
for ENV in $@; do

    # creates a list of the packages in the specified directory, adding a date stamp
    echo -e "\n${BOLD}Exporting packages' list in ${CYAN}${ENV}${RESET}${BOLD}...${RESET}"
    conda list --export > "${CONDA_ENVS_BACKUP_DIR}/${ENV}_backup_$(date +"%Y-%m-%d").yml"

    # removes the ENV: DOES NOT ASK FOR CONFIRMATION!
    echo "${BOLD}Deleting environment ${CYAN}${ENV}${RESET}${BOLD}...${RESET}"
    conda env remove --name "${ENV}"
 
done
