#! /usr/bin/env bash
# updates every package out of all the list of conda environments.

# this is necessary, otherwise won't find the command. see here:
# https://github.com/conda/conda/issues/7980#issuecomment-441358406
source "$CONDA_ROOT/etc/profile.d/conda.sh"

# sourcing variables to make formatted output
source "$ZDOTDIR/colors.zsh"

echo -e "\n${BOLD}Fetching the environments...${RESET}\n"

# lists all environments with conda
    # awk is used to fetch only env names
    # sed used to:
    # - delete lines starting with #
    # - delete blank lines (^$)
CONDA_ENVS="$(conda env list | awk '{print $1}' | sed -e '/#/d' -e '/^$/d')" 

for env in $CONDA_ENVS;
do
    # ${RESET}${BOLD} is meant to produce white highlight (otherwise it is just too dim)
    echo -e "${BOLD}${CYAN}==> ${RESET}${BOLD}Checking for packages to update in ${CYAN}$env${RESET}...\n"
    conda update --all -n $env -y;
    echo -e "${BOLD}Packages in ${CYAN}$env ${RESET}${BOLD}are up to date.${RESET}\n"
done

echo -e "${BOLD}Environments have been updated. Cleaning the tarballs... ${RESET}\n"

conda clean --all -y

echo -e "\n${BOLD}Tarballs removed.${RESET}"
