#! /usr/bin/env bash

# this script takes as input a column and the file it comes from and counts the frequencies of its elements.

# define inputs
_INPUT_COLS=$1
_INPUT_FILE=$2

# function
xsv select "$_INPUT_COLS" "$_INPUT_FILE" | sort | uniq -c | sort -nr | xsv table
