#! /usr/bin/env zsh

create_index(){

    local folder="$1"
    local extension="$2"
    local destination_file="index-${folder}.csv"

    echo "item_name" > "$destination_file"

    fd . --extension="$extension" "$folder" \
        | sed 's/\(.*\)\/\(.*\)/\2/' >> "$destination_file"

    }

create_index "$1" "$2"
