#! /usr/bin/env bash

# +------------------+
# | DEFINE FUNCTIONS |
# +------------------+

_start_server () {

    #checks if the server is running
    if [[ "$(pg_ctl status)" == "pg_ctl: no server running" ]]; then
        echo -e "\n${BOLD}${RED}==> Postgres server is not running, starting the server...${RESET}"
        # starts the server, deletes output
        pg_ctl start -D /usr/local/var/postgres > /dev/null 2>&1
    else
        echo -e "\n${CYAN}${BOLD}==> Postgres server is already running.${RESET}"
    fi

    # lists where postgres binary and server location are
    local pg_status
    pg_status=$(pg_ctl status -D /usr/local/var/postgres | sed "s/\"//g" |  awk "NR==2")

    echo -e "\n${BOLD}${WHITE}PostgreSQL binary:${BLUE}$(echo "$pg_status" | awk 'BEGIN { FS = " " } ; {print $1}')${RESET}
    ${BOLD}${WHITE}Server directory:${BLUE}$(echo "$pg_status" | awk 'BEGIN { FS = " " } ; {print $3}')${RESET}"

}

_create_schema () {
    
    local db_name="$1"
    local schema_name="$2"

    if [[ -z "${schema_name}" ]]
    then
        psql -d "$db_name" -c "CREATE SCHEMA IF NOT EXISTS ${schema_name};"
    fi

    psql -d "$db_name" -c "
        ALTER DATABASE ${db_name} SET timezone TO 'Europe/Rome';
        ALTER DATABASE ${db_name} SET search_path TO \"\$user\", ${schema_name}, public;
    "

}

_create_table () {

    # define parameters
    local db_name="$1"
    local table_name="$2"

    echo -e "\n${BOLD}${BLUE}=>${WHITE} Checking if table ${BLUE}${table_name}${WHITE} exists${RESET}"
    psql -d "$db_name" -c "
        CREATE TABLE IF NOT EXISTS ${table_name} (
            bici SMALLINT,
            tipo_bici VARCHAR(20),
            cliente_anonimizzato SMALLINT,
            data_prelievo TIMESTAMPTZ,
            numero_stazione_prelievo SMALLINT,
            nome_stazione_prelievo TEXT,
            data_restituzione TIMESTAMPTZ,
            numero_stazione_restituzione SMALLINT,
            nome_stazione_restituzione TEXT,
            distanza_totale REAL
        );" 
    echo ""

}

_copy_csv_into_postgres () {

    # define parameters
    local csv="$1"
    local table_name="$2"
    local db_name="$3"

    # store the columns of the csv as an array
    local cols
    cols="$( head -1 "$csv" )"
    
    # copy the csv into the postgresql TABLE_NAME into the database DB_NAME
    echo "${BOLD}${CYAN}==> ${WHITE}Copying ${CYAN}${csv} ${WHITE}to ${BLUE}${table_name} ${WHITE}in ${VIOLET}${db_name}${RESET}"
    psql -d "$db_name" -c "SET datestyle TO iso, dmy; COPY ${table_name}(${cols}) FROM '${PWD}/${csv}' DELIMITER ',' CSV HEADER;"

}

# +-------------+
# | SCRIPT BODY |
# +-------------+

# shellcheck source=formatting_colors
source formatting_colors

_DB_NAME="bikemi"
_SCHEMA_NAME="bikemi_rentals"
_TABLE_NAME="bikemi_source_data"

_start_server

_create_schema "$_DB_NAME" "$_SCHEMA_NAME"

_create_table "$_DB_NAME" "$_TABLE_NAME"

for _DIR in "$@"; do

    pushd "$_DIR" 1>/dev/null || exit 

    for _CSV in *.csv ; do
        _copy_csv_into_postgres "$_CSV" "$_TABLE_NAME" "$_DB_NAME"
        echo ""
    done

    popd 1>/dev/null || exit

done 
