#! /usr/bin/env bash

_create_table_if_not_exists () {

    # define parameters
    TABLE_NAME="$1"
    DB_NAME="$2"

    echo -e "\n${BOLD}${BLUE}=>${WHITE} Checking if table ${BLUE}${TABLE_NAME}${WHITE} exists${RESET}"
    psql -c "SET datestyle TO iso, dmy;

        CREATE TABLE IF NOT EXISTS ${TABLE_NAME} (
            bici INT,
            tipo_bici VARCHAR(20),
            cliente_anonimizzato INT,
            data_prelievo TIMESTAMP,
            numero_stazione_prelievo INT,
            nome_stazione_prelievo TEXT,
            data_restituzione TIMESTAMP,
            numero_stazione_restituzione INT,
            nome_stazione_restituzione TEXT,
            distanza_totale REAL
        );" "$DB_NAME" 
    echo ""

}

_copy_csv_into_postgres () {

    # define parameters
    CSV="$1"
    TABLE_NAME="$2"
    DB_NAME="$3"

    # store the columns of the csv as an array
    COLS="$( head -1 "$CSV" )"
    
    # copy the csv into the postgresql TABLE_NAME into the database DB_NAME
    echo "${BOLD}${CYAN}==> ${WHITE}Copying ${CYAN}${CSV} ${WHITE}to ${BLUE}${TABLE_NAME} ${WHITE}in ${VIOLET}${DB_NAME}${RESET}"
    psql -c "SET datestyle TO iso, dmy; COPY ${TABLE_NAME}(${COLS}) FROM '${PWD}/${CSV}' DELIMITER ',' CSV HEADER;" "$DB_NAME"

}

# shellcheck source=formatting_colors
source formatting_colors

TABLE_NAME="bikemi_rentals"
DB_NAME="bikemi"

_create_table_if_not_exists "$TABLE_NAME" "$DB_NAME"

for DIR in "$@"; do

    pushd "$DIR" 1>/dev/null || exit 

    for CSV in *.csv ; do
        _copy_csv_into_postgres "$CSV" "$TABLE_NAME" "$DB_NAME"
        echo ""
    done

    popd 1>/dev/null || exit

done 