#!/usr/bin/env bash

# =================
# | EXAMPLE USAGE |
# =================

# from_excel_to_postgres path/to/zipfile1 path/to/zipfile2

# ==============================
# | DEFINE AUXILIARY FUNCTIONS |
# ==============================

_start_server () {

    #checks if the server is running
    if [[ "$(pg_ctl status)" == "pg_ctl: no server running" ]]; then
        echo -e "\n${BOLD}${RED}==> Postgres server is not running, starting the server...${RESET}"
        # starts the server, deletes output
        pg_ctl start -D /usr/local/var/postgres > /dev/null 2>&1
    else
        echo -e "\n${CYAN}${BOLD}==> Postgres server is already running.${RESET}"
    fi

    # lists where postgres binary and server location are
    local pg_status
    pg_status=$(pg_ctl status -D /usr/local/var/postgres | sed "s/\"//g" |  awk "NR==2")

    echo -e "\n${BOLD}${WHITE}PostgreSQL binary:${BLUE}$(echo "$pg_status" | awk 'BEGIN { FS = " " } ; {print $1}')${RESET}
    ${BOLD}${WHITE}Server directory:${BLUE}$(echo "$pg_status" | awk 'BEGIN { FS = " " } ; {print $3}')${RESET}"

}

_create_schema () {
    
    local db_name="$1"
    local schema_name="$2"

    if [[ -z "${schema_name}" ]]
    then
        psql -d "$db_name" -c "CREATE SCHEMA IF NOT EXISTS ${schema_name};"
    fi

    psql -d "$db_name" -c "
        ALTER DATABASE ${db_name} SET timezone TO 'Europe/Rome';
        ALTER DATABASE ${db_name} SET search_path TO \"\$user\", ${schema_name}, public;
    "

}

_create_table () {

    # define parameters
    local db_name="$1"
    local table_name="$2"

    echo -e "\n${BOLD}${BLUE}=>${WHITE} Checking if table ${BLUE}${table_name}${WHITE} exists${RESET}"
    psql -d "$db_name" -c "
        CREATE TABLE IF NOT EXISTS ${table_name} (
            bici INT,
            tipo_bici VARCHAR(20),
            cliente_anonimizzato SMALLINT,
            data_prelievo TIMESTAMPTZ,
            numero_stazione_prelievo SMALLINT,
            nome_stazione_prelievo TEXT,
            data_restituzione TIMESTAMPTZ,
            numero_stazione_restituzione SMALLINT,
            nome_stazione_restituzione TEXT,
            distanza_totale REAL
        );" 
    echo ""

}

_unzip_all () {

    local path_to_zip="$1"
    local path_to_extraction="$2"

    echo "${BOLD}${BLUE}=> ${WHITE}Create the extraction directory ${BLUE}${path_to_extraction}${RESET}"
    mkdir -p "$path_to_extraction"

    # unzip the file into the extraction directory
    echo -e "\n${BOLD}${BLUE}=> ${WHITE}Unzip ${BLUE}${path_to_zip}${RESET}"
    unzip "$path_to_zip" -d "$path_to_extraction"
    echo ""

}

_clean_headers () {

    # redefine inputs
    local file="$1"

    # takes the header of the file and changes it to snake-case
    local new_header
    new_header=$(head -1 "$file" | tr "[:upper:]" "[:lower:]" | tr " " "_") 

    # substitutes to the first row of the csv the newly formatted one; then outputs the file.
    # note that sed requires creating a backup file (ending with .bak): we remove it
    sed -i .bak "1s/.*/$new_header/" "$file" && rm "${file}.bak"

}

_turn_xlsx_into_csv () {

    # redefine input(s)
    local xlsx="$1"
    # the name of the temporary csv
    local temp_csv="${xlsx/.xlsx/_temp.csv}"
    # the name of the output csv
    local csv="${temp_csv/_temp}"

    # 1. convert the .xlsx into a _temp.csv file, then remove the .xlsx file
    echo "${BOLD}${GREEN}==> ${WHITE}Convert ${GREEN}${xlsx} ${WHITE}to ${GREEN}${temp_csv}${RESET}"
    in2csv "$xlsx" > "${temp_csv}" && rm "$xlsx"

    # 2. turn the _temp.csv header into snakecase ('Column Name' -> 'column_name')
    echo "${BOLD}${GREEN}==> ${WHITE}Clean ${GREEN}${temp_csv} ${WHITE}headers${RESET}"
    _clean_headers "${temp_csv}"

    # 3. selects only the columns needed
    echo "${BOLD}${GREEN}==> ${WHITE}Select the columns and remove incompatible rows from ${GREEN}${temp_csv}${RESET}"
    xsv search -v -s 1 '^[a-zA-Z]' "${temp_csv}" | \
        xsv select "1-3,5-7,10-12,15" "${temp_csv}" > "${csv}" && rm "${temp_csv}"

} 

_copy_csv_into_postgres () {

    # define parameters
    local csv="$1"
    local table_name="$2"
    local db_name="$3"

    # store the columns of the csv as an array
    local cols
    cols="$( head -1 "$csv" )"
    
    # copy the csv into the postgresql TABLE_NAME into the database DB_NAME
    echo "${BOLD}${CYAN}==> ${WHITE}Copying ${CYAN}${csv} ${WHITE}to ${BLUE}${table_name} ${WHITE}in ${VIOLET}${db_name}${RESET}"
    psql -d "$db_name" -c "SET datestyle TO iso, dmy; COPY ${table_name}(${cols}) FROM '${PWD}/${csv}' DELIMITER ',' CSV HEADER;"

}

_zip_csvs_and_remove_dir () {

    local exec_dir="$1"

    # zip recursively all files in the extraction dir
    echo -e "${BOLD}${BLUE}=>${WHITE} Backing up ${BLUE}${exec_dir}${RESET}"
    zip -9 "${exec_dir}_csv.zip" "${exec_dir}"/*.csv && rm -rf "$exec_dir"

}

# ===============
# | SCRIPT BODY |
# ===============

# colored output "trick"
source "./formatting_colors"

# 1. define variables for postgres
_DB_NAME="bikemi"
_SCHEMA_NAME="bikemi_rentals"
_TABLE_NAME="bikemi_source_data"

_start_server
_create_schema "$_DB_NAME" "$_SCHEMA_NAME"
_create_table "$_DB_NAME" "$_TABLE_NAME"

for _ZIP_PATH in "$@"; do

    _EXTRACTION_DIR="${_ZIP_PATH/.zip}" 
    _unzip_all "$_ZIP_PATH" "$_EXTRACTION_DIR"

    pushd "$_EXTRACTION_DIR" 1>/dev/null || exit

    for _FILE in * ; do
        echo "${BOLD}${CYAN}==> ${WHITE}Renaming ${CYAN}${_FILE}${RESET}"
        rename -z "$_FILE"
    done
    echo ""

    for _XLSX in *.xlsx ; do
        _turn_xlsx_into_csv "$_XLSX"
        echo ""
    done

    for _CSV in *.csv ; do
        _copy_csv_into_postgres "$_CSV" "$_TABLE_NAME" "$_DB_NAME"
    done

    pushd .. 1>/dev/null || exit

    _zip_csvs_and_remove_dir "$_EXTRACTION_DIR"

    # move back to the original directory
    pushd +2 1>/dev/null || exit
    
done
