#!/usr/bin/env zsh
#
# reference: https://junegunn.github.io/fzf/tips/ripgrep-integration/

main() {
    # {q} = query
    RELOAD='reload:rg --column --color=always --smart-case -- {q} || :'
    OPENER='
        if [[ -$FZF_SELECT_COUNT -eq 0 ]] then
            nvim {1} +{2}
        else
            nvim +cw -q {+f}
        fi

    '
    fzf \
        --multi \
        --disabled \
        --ansi \
        --bind="start:$RELOAD" \
        --bind="change:$RELOAD" \
        --bind="enter:become:$OPENER" \
        --bind="ctrl-a:select-all,ctrl-d:deselect-all,ctrl-/:toggle-preview" \
        --delimiter=":" \
        --preview="bat --style=numbers --color=always --highlight-line={2} -- {1}" \
        --preview-window="+{2}/2,<80(up)" \
        --query="$*"
}

main "$*"
