#!/usr/bin/env zsh

main() {
    requires fd fzf bat nvim

    fd --hidden --exclude=.git --type=file -- $* | \
    fzf \
        --ansi \
        --tmux=90% \
        --bind="enter:become:nvim -- {}" \
        --bind="ctrl-/:toggle-preview" \
        --preview="bat --style=numbers --color=always -- {}" \
        --preview-window="<80(up)" \
        --query="${*:-}"
}

main "${*:-}"
