#! /usr/bin/env bash

_get_bikemi_stalls_data () {

    local url="$1"
    local filename="$2"

    curl "$url" -o "$filename"
}

_process_stalls_data () {
    
    local target_file="$1"
    local destination_file="$2"
    local new_header="id_nil,nil,geometry"

    xsv select 1,2,11 --delimiter ";" "$target_file" | \
        sed "1s/.*/$new_header/" > "$destination_file" \
        && rm "$target_file"

}

_start_server () {

    local server="${1:-"/usr/local/var/postgres"}"

    #checks if the server is running
    if [[ "$(pg_ctl status)" == "pg_ctl: no server running" ]]; then
        echo -e "\n${BOLD}${RED}==> Postgres server is not running, starting the server...${RESET}"
        # starts the server, deletes output
        pg_ctl start -D "$server" > /dev/null 2>&1
    else
        echo -e "\n${CYAN}${BOLD}==> Postgres server is already running.${RESET}"
    fi

}

_create_table () {

    # define parameters
    local table_name="$1"
    local db_name="$2"

    echo -e "\n${BOLD}${BLUE}=>${WHITE} Checking if table ${BLUE}${table_name}${WHITE} exists${RESET}"
    psql -d "$db_name" -c "
        CREATE TABLE IF NOT EXISTS ${table_name} (
            id_nil SMALLINT PRIMARY KEY
            , nil TEXT
            , geometry TEXT
        );" 
    echo ""

}

_import_data_into_postgres () {
    
    # define parameters
    local csv="$1"
    local table_name="$2"
    local db_name="$3"

    # store the columns of the csv as an array
    local cols
    cols="$( head -1 "$csv" )"
    
    # copy the csv into the postgresql TABLE_NAME into the database DB_NAME
    echo "${BOLD}${CYAN}==> ${WHITE}Copying ${CYAN}${csv} ${WHITE}to ${BLUE}${table_name} ${WHITE}in ${VIOLET}${db_name}${RESET}"
    psql -d "$db_name" -c "
        SET datestyle TO iso, dmy;
        COPY ${table_name}(${cols})
        FROM '${PWD}/${csv}'
        DELIMITER ','
        CSV HEADER;" \
        && rm "$csv"
}

# colored output
source "./formatting_colors"

# define global variables

_URL="https://dati.comune.milano.it/dataset/e8e765fc-d882-40b8-95d8-16ff3d39eb7c/resource/3fce7202-0076-4a7b-ac2c-d2ab9b5dc658/download/ds964_nil_wm_4326.csv"

_TARGET_DIR="${1:-"$HOME/tesi/data/milan"}"
_FILE_NAME="${2:-"administrative-nils.csv"}"
_PROCESSED_FILE="${_FILE_NAME}.tmp"

_DB_NAME="bikemi"
_TABLE_NAME="milan_nils"
_SERVER="/usr/local/var/postgres"

# script body
pushd "$_TARGET_DIR" 1>/dev/null || exit

_get_bikemi_stalls_data "$_URL" "$_FILE_NAME" && _process_stalls_data "$_FILE_NAME" "$_PROCESSED_FILE" || exit

_start_server "$_SERVER"

_create_table "$_TABLE_NAME" "$_DB_NAME" && _import_data_into_postgres "$_PROCESSED_FILE" "$_TABLE_NAME" "$_DB_NAME"

popd 1>/dev/null || exit