#! /usr/bin/env zsh

command -v julia 1>/dev/null || {
        rich "[bold red] julia binary not found. please install julia![/bold red]"
    }


julia_notebook(){

    local project_dir="$1"

    julia --project="$project_dir" -e "using IJulia; notebook(dir=\"$project_dir\")"

    }

_PROJECT_DIR="${1:-"."}"

julia_notebook _PROJECT_DIR
