#! /usr/bin/env bash

# +------------------+
# | Define Functions |
# +------------------+

_check_target_dirs () {

  local notebook_dir="$1"
  local conversion_dir="$2"

  if [[ ! -d "$notebook_dir" ]] ; then
      echo "${BOLD}${RED}${notebook_dir}${RESET}${BOLD} does not exist. Please insert a valid path."
      exit
  fi

  # if the target directory does not exist, create it
  [[ -d "$conversion_dir" ]] || mkdir "$conversion_dir"

}

_pair_notebooks () {

    local _input_file="$1"
    local _to_format="$2"
    local _conversion_dir="$3"

    local _extension="${_to_format%:*}"

    # the file is always passed as notebook_dir/_input_file.ipynb so we take the basename
    # then we replace the first file extension .ipynb with the format for the conversion
    # ${var%pattern/replacement} matches the first pattern from the end!
    local _filename
    _filename="$(basename "$_input_file")"

    local _output_file="${_filename/.ipynb/.$_extension}"

    if [[ ! -e "${_conversion_dir}/${_output_file}" ]] ; then
        
        echo "${BOLD}${BLUE}==>${RESET}${BOLD} Pairing ${BLUE}${_filename}${RESET}${BOLD} to ${BLUE}${_output_file}${RESET}"
        
        # pair the notebook from the execution dir to the desired format in the destination dir
        jupytext --set-formats \
        "$(dirname "$_input_file")"///ipynb,"$_conversion_dir"///"$_to_format" \
        "$_input_file"
        
        # just add a blank line
        echo ""
    fi
}

_update_sync () {

    local _input_file="$1"
    local _to_format="${2%:*}"     # replace the trailing `:...` with nothing
    local _conversion_dir="$3"

    # the file is always passed as notebook_dir/input_file.ipynb so we take the basename
    # then we replace the first file extension .ipynb with the format for the conversion
    # ${var%pattern/replacement} replaced the first pattern from the end, i.e. trailing pattern
    local _filename
    _filename="$(basename "$_input_file")"
    
    local _output_file="${_filename/.ipynb/.$_to_format}"

    echo -e "${BOLD}${CYAN}==>${RESET}${BOLD} Updating sync between ${CYAN}${_filename}${RESET}${BOLD} and ${CYAN}${_output_file}${RESET}"
    
    jupytext --sync "$_input_file"
    
    echo ""
}

main () {

  local to_format="$1"
  local notebook_dir="$2"
  local conversion_dir="$3"

  while true ; do

      echo -e "\n${BOLD}Pair or sync ${YELLOW}'.ipynb' notebooks${RESET}${BOLD} in ${BLUE}${_ROOT_DIR}/${notebook_dir}${RESET}${BOLD} and ${YELLOW}'${to_format}'${RESET}${BOLD} files in ${BLUE}${_ROOT_DIR}/${conversion_dir}.${RESET}"
      read -rp "${BOLD}Do you want to ${VIOLET}pair [p]${RESET}${BOLD} notebooks or ${VIOLET}sync [s]${RESET}${BOLD} the recent updates? ${VIOLET}[p/s]${RESET} " answer
      echo ""

      case $answer in
          [pP]* ) for ipynb in "$notebook_dir"/*.ipynb ; do
                      _pair_notebooks "$ipynb" "$to_format" "$conversion_dir"
                  done

                  break;;

          [sS]* ) for ipynb in "$notebook_dir"/*.ipynb ; do
                      _update_sync "$ipynb" "$to_format" "$conversion_dir"
                  done

                  break;;

              * ) echo "Enter P or S, please.";;
      esac
  done
}


# +----------------+
# | Before running |
# +----------------+

source "formatting-colors" # for coloured output
  
# +----------------+
# | Define Globals |
# +----------------+

_TARGET_DIR="${1:-"$HOME/tesi/notebooks"}"
_TO_FORMAT="${2:-"md:myst"}"
_CONVERSION_DIR="${3:-"body"}"

_ROOT_DIR="$(dirname "$_TARGET_DIR")"
_NB_DIR="$(basename "$_TARGET_DIR")"

# +------+
# | Body |
# +------+

pushd "$_ROOT_DIR" 1>/dev/null || exit

_check_target_dirs "$_NB_DIR" "$_CONVERSION_DIR"

main "$_TO_FORMAT" "$_NB_DIR" "$_CONVERSION_DIR"

popd 1>/dev/null || exit
