#! /usr/bin/env bash

# saves the packages of an environment to a specified directory and removes it.

# this is necessary, otherwise won't find the command. see here:
# https://github.com/conda/conda/issues/7980#issuecomment-441358406
. "$CONDA_ROOT/etc/profile.d/mamba.sh"

. formatting-colors # for colored output

_CONDA_ENVS_CACHE="${CACHE}/conda_envs_backups"

# check if the directory where the package list exists, else make it
if [[ ! -d "$_CONDA_ENVS_CACHE" ]]; then
    echo -e "\nBackup directory created at \"${_CONDA_ENVS_CACHE}\"."
    mkdir -p "${_CONDA_ENVS_CACHE}"
else
    echo -e "\nBackup directory already exists at \"${_CONDA_ENVS_CACHE}\"."
fi

# $@ indicates every argument of the script
for _ENV in "$@"; do

    # creates a list of the packages in the specified directory, adding a date stamp
    echo -e "\n${BOLD}Exporting packages' list in ${CYAN}${_ENV}${RESET}${BOLD}...${RESET}"
    mamba list --export >"${_CONDA_ENVS_CACHE}/${_ENV}_backup_$(date +"%Y-%m-%d").yml"

    # removes the ENV: DOES NOT ASK FOR CONFIRMATION!
    echo "${BOLD}Deleting environment ${CYAN}${_ENV}${RESET}${BOLD}...${RESET}"
    mamba env remove --name "${_ENV}"

done
