#! /usr/bin/env bash
# updates every package out of all the list of conda environments.

update_all_envs(){
    echo -e "\n${BOLD}Fetching the environments...${RESET}\n"
    
    # take all environments except base
    local conda_envs
    conda_envs="$(mamba env list | awk 'NR > 3 { print $1 }')"
    
    echo -e "${BOLD}Environments to update:\n${CYAN}${conda_envs}${RESET}\n"
    
    for env in $conda_envs ; do

        echo -e "${BOLD}${CYAN}==> ${RESET}${BOLD}Checking for packages to update in ${CYAN}$env${RESET}...\n"

        mamba update --all -n "$env" -y -c conda-forge;
        
        echo -e "${BOLD}Packages in ${CYAN}$env${RESET}${BOLD} are up to date.${RESET}\n"
    
    done
} 

clean_all () {
    echo -e "${BOLD}Environments have been updated. Cleaning the tarballs... ${RESET}\n"
    
    mamba clean --all -y
    
    echo -e "\n${BOLD}Tarballs removed.${RESET}"
}

# this is necessary, otherwise won't find the command. see here:
# https://github.com/conda/conda/issues/7980#issuecomment-441358406
source "$CONDA_ROOT/etc/profile.d/conda.sh"
source "$CONDA_ROOT/etc/profile.d/mamba.sh"

# sourcing variables to make formatted output
source formatting_colors 

update_all_envs

clean_all

