#! /usr/bin/env bash

# saves the packages of an environment to a specified directory and removes it.

# this is necessary, otherwise won't find the command. see here:
# https://github.com/conda/conda/issues/7980#issuecomment-441358406
. "$CONDA_ROOT/etc/profile.d/mamba.sh"

command -v rich 1>/dev/null || {
    echo "Install rich first, e.g. \`pipx install rich\`"
    exit 1
}

_check_cache_dir() {

    local cache_dir="$1"

    if [[ ! -d "$cache_dir" ]]; then
        echo
        rich --print "Creating directory: [bold][green]${cache_dir}[/green]." &&
            mkdir -p "$cache_dir"
    else
        echo
        rich --print "Backup directory exists at [bold][green]${cache_dir}[/green]."
    fi

}

_CONDA_ENVS_CACHE="${CACHE}/conda_envs_backups"

_check_cache_dir "${_CONDA_ENVS_CACHE}"

for _ENV in "$@"; do

    # creates a list of the packages in the specified directory, adding a date stamp
    echo
    rich --print "[bold]Exporting packages' list in [blue]${_ENV}[/blue]..."
    mamba env export -n "$_ENV" >"${_CONDA_ENVS_CACHE}/${_ENV}_backup_$(date +"%Y-%m-%d").yml"

    # removes the ENV: DOES NOT ASK FOR CONFIRMATION!
    echo
    rich --print --emoji ":warning: [bold][red]Deleting[/red] environment [blue]${_ENV}[/blue]..."
    mamba env remove --name "$_ENV"

done
