#! /usr/bin/env bash

# if no input is specified, updates every package in every conda environment
# otherwise, updates just the packages inside the environments you specify.

update_envs() {

    local conda_envs=("$@")

    echo &&
        rich --print "[bold]Environments to update: [bold cyan]${conda_envs[*]}" &&
        echo

    for env in "${conda_envs[@]}"; do

        rich --print "[bold][cyan]==>[/cyan] Checking for packages to update in [cyan]${env}[/cyan]..." &&
            mamba update --all -n "$env" -y --no-banner -c conda-forge &&
            rich --print "[bold]Packages in [cyan]${env}[/cyan] are up to date." &&
            echo

    done
}

clean_all() {

    rich --print "[bold]Environments have been updated. Cleaning the tarballs..." &&
    mamba clean --all -y --no-banner &&
    rich --print "[bold]Tarballs have been cleaned."

}

# this is necessary, otherwise won't find the command.
# both conda.sh and mamba.sh need to be sourced
# https://github.com/conda/conda/issues/7980#issuecomment-96682413
. "$CONDA_ROOT/etc/profile.d/conda.sh"
. "$CONDA_ROOT/etc/profile.d/mamba.sh"

command -v rich 1>/dev/null || {
    echo "Install rich first, e.g. \`pipx install rich\`"
    exit 1
}

if [[ "$#" -eq 0 ]]; then
    # grab the list of envs.
    # NR < $0 because conda prints one blank line last
    # tr is used to obtain one string with ";" as separators
    _ENVS_STR=$(mamba env list | awk 'NR > 2 && NR < $0 { print $1 }' | tr "\n" ";")

    # read as array using ";" as separator
    IFS=";" read -ra _ENVS_ARR <<<"$_ENVS_STR"
else
    _ENVS_ARR=("$@")
fi

update_envs "${_ENVS_ARR[@]}"

clean_all
