#! /usr/bin/env zsh

n() {
	requires nvim

	if [[ -z "$1" ]]; then
		nvim -c 'Telescope find_files'
	elif [[ -d "$1" ]]; then
		nvim -c "Telescope find_files cwd=$1"
	else
		nvim -- "$1"
	fi
}

n "$1"
