#! /usr/bin/env zsh

nn() {
	requires nvim

	if [[ -z "$1" ]]; then
		nvim -c 'Telescope live_grep'
	elif [[ -d "$1" ]]; then
		nvim -c "Telescope live_grep cwd=$1"
	else
		nvim -c 'Telescope current_buffer_fuzzy_find' -- "$1"
	fi
}

nn "$1"
