#! /usr/bin/env bash

command -v rich || {
    echo "Install rich first, e.g. \`pipx install rich\`"
    exit 1
}

_SERVER=${1:-"/usr/local/var/postgres"}

#checks if the server is running
if [[ "$(pg_ctl status)" == "pg_ctl: no server running" ]]; then
    echo &&
        rich --print "[bold][red]==>[/red] Starting server at ${_SERVER}..." &&
        pg_ctl start -D "$_SERVER" >/dev/null 2>&1
else
    echo &&
        rich --print "[bold][cyan]==>[/cyan] Server is already running."
fi
