#! /usr/bin/env bash

command -v rich || {
    echo "Install rich first, e.g. \`pipx install rich\`"
    exit 1
}

#checks if the server is running
if [[ "$(pg_ctl status)" == "pg_ctl: no server running" ]]; then
    echo &&
        rich --print "[bold][red]==>[/red] Postgres server is not running, starting the server..." &&
        pg_ctl start -D /usr/local/var/postgres >/dev/null 2>&1
else
    echo &&
        rich --print "[bold][cyan]==>[/cyan] Postgres server is already running."
fi
