#! /usr/bin/env zsh

tmux-switcher () {
    local session="$(tmux list-sessions -F "#{session_name}"| fzf --tmux=center --ansi)"

    if [[ -z "$session" ]]; then
        return
    fi

    if [[ ! -z "$TMUX" ]]; then
        tmux switch-client -t "$session"
    else
        tmux attach -t "$session"
    fi
}

tmux-switcher
