#! /usr/bin/env zsh

tmux-sessionizer() {
    requires zoxide sk tmux

    local ignores=(
        ".DS_Store"
        ".Rproj.user"
        ".git"
        ".idea"
        ".ipynb_checkpoints"
        ".mypy_cache"
        ".pytest_cache"
        ".ruff_cache"
        ".terraform"
        ".venv"
        ".vscode"
        "__pycache__"
        "assets"
        "debug/"
        "node_modules/"
        "raycast"
        "renv/"
        "target/"
        "venv"
    )

    local sk_args=(
        --ansi
        --height=40%
        --preview="eza --color --all --group-directories-first --icons --level=2 --tree --ignore-glob='${(j:|:)ignores}' -- {}"
        --preview-window=down,40%
        --cmd="zoxide query --list"
    )

    local dir
    local dirname
    dir="$(sk "${sk_args[@]}")"
    dirname="$(basename "${dir/./}")"

    if [[ -z "$dir" ]]; then
        return 1
    fi

    local tmux_running
    tmux_running=$(pgrep tmux)

    if [[ -z $TMUX ]] && [[ -z $TMUX_RUNNING ]]; then
        tmux new-session -s "$dirname" -c "cd $dir"
        exit 0
    fi

    if ! tmux has-session -t=$dirname 2> /dev/null; then
        tmux new-session -ds $dirname -c $dir
    fi

    tmux switch-client -t $dirname
}

tmux-sessionizer
