#! /usr/bin/env zsh

tmux-switcher () {
    local session="$(tmux list-sessions | cut -d ":" -f 1 | fzf --ansi --height=40%)"

    if [[ ! -z "$TMUX" ]]; then
        tmux switch-client -t "$session"
    fi

    tmux attach -t "$session"
}

tmux-switcher
