#! /usr/bin/env zsh

tmux-sessionizer() {
    requires zoxide tmux

    local dir dirname

    dir="$(fzf-zoxide)"
    dirname="$(basename "${dir/./}")"

    if ! tmux has-session -t "$dirname" 2>/dev/null ; then
        tmux new-session -d -s "$dirname" -c "$dir"
    fi

    if [[ ! -z "$TMUX" ]]; then
        tmux switch-client -t "$dirname"
    fi

    tmux attach -t "$dirname"
}


tmux-sessionizer
