#! /usr/bin/env bash

_EXEC_DIR=${1:-"$HOME/tesi/notebooks"}

pushd "$_EXEC_DIR" 1>/dev/null || exit

echo -e "Trusting notebooks in $_EXEC_DIR\n"

for NOTEBOOK in *.ipynb ; do
    jupyter trust "$NOTEBOOK"
    done

popd 1>/dev/null || exit